#!/bin/bash

# qgm-tuecrypt
# Ein kleines Skript, um die Verwendung von Truecrypt auf 
# Linux-Clients zu vereinfachen
#
# GPLv3 Frank Schiebel <frank@linuxmuster.net> 2015-06-16 
#

# Konfiguration 
# Name der Containerdatei
CONTAINERNAME="qgm-encrypted.tc"
# Benutzerhome (als Variable, falls man das mal in eine Option 
# auslagern möchte)
USERHOME=$HOME
# Mountverzeichnis
MOUNTUSBTO="$USERHOME/USB-verschluesselt"

# Kommandozeilenargumente
action="mount"
while getopts 'dc' OPT; do
  case $OPT in
    c)  action="create";;
    d)  action="umount";;
    *)  unknown="yes";;
  esac
done


#
# mount_container Container einbinden
#
# Diese Funktion sucht in den entfernbaren 
# Medien nach einer Datei mit dem Namen 
# $CONTAINERNAME und bindet diese ein.
#
function mount_container () {
	# Suche den Container unterhalb von /media, nur der erste gefundene wird autoatisch verwaltet!
	CONTAINER=$(find /media -name $CONTAINERNAME ! -path "*.Trash*" 2> /dev/null | head -n 1)
    
    # Kein Container gefunden - jetzt wird einer angelegt!
	if [ "x$CONTAINER" = "x" ]; then 
		create_new_container 
        mount_container
		exit
	fi

    # Prüfe, ob der Container bereits gemountet ist
	CONTAINER_MOUNTED=$(truecrypt -t -l | grep $CONTAINER)
    # Wenn ja, Hinweis an den Anwender, Fragen, ob der Container ausgeworfen werden soll
	if [ "x$CONTAINER_MOUNTED" != "x" ]; then 
		zenity  --question --window-icon="info" --text="Der Container ist bereits eingebunden!\n\nMöchten Sie den Container auswerfen?"
        # Wenn Antort aus zenity "Ja" ist, Container auswerfen
		if [ $? -eq 0 ]; then 
			umount_container
		fi
        # Sonst Skript beenden
		exit 0
	fi 


	# Verzeichnis anlegen
	mkdir -p $MOUNTUSBTO
	# Container einbinden. TC fragt dabei 
    # grafisch nach dem Passwort für den Container
	sudo truecrypt $CONTAINER $MOUNTUSBTO
}

#
# umount_container Container aushängen
#
# Diese Funktion entfernt den TC-Container und 
# Informiert den Benutzer. 
# Auf Nachfrage kann das USB Gerät gleich 
# ausgehängt werden
#
function umount_container () {	
	sudo truecrypt -d $CONTAINER && zenity  --question --text="Der verschlüsselte Container wurde sicher ausgeworfen.\n\nWollen Sie den USB Stick ebenfalls auswerfen?"
	if [ $? -eq 0 ]; then 
        DEVICEPATH=$(find /media -name qgm-encrypted.tc 2> /dev/null | head -n 1)
        DEVICEPATH=${DEVICEPATH%/*}
        # Das wird wahrscheinlich nicht gehen, ohne sudo....
		umount $DEVICEPATH
	fi

}

#
# create_new_container Container erzeugen
#
function create_new_container () {
    # Suche eingehängte Massenpeichergeräte
    MOUNTPOINT=$(mount | grep "on /media" | awk -F"type" '{print $1}' | awk -F"on" '{print $2}' | sed -e "s/^ //"| sed -e "s/ $//" | head -n 1)
    # Wenn keine gefunden werden: Informiere den Benutzer und beende das Skript
    # FIXME zenity Rückmeldung
	if [ "x$MOUNTPOINT" = "x" ]; then 
        zenity  --notification \
                --window-icon="info" \
                --text="Es wurde kein Massenspeichermedium gefunden. Stellen Sie sicher dass der USB-Stick angeschlossen ist."
		exit 1
	fi
    # Freien Platz auf dem Ziellaufwerk ermitteln
    FREE=$(df "$MOUNTPOINT" | awk '{print $4}' | tail -n 1)
    FREEMB=$((FREE / 1024 ))
    # Minimalwert des Schiebereglers
    MINMB=64
    # Maximalwert des Schiebelreglers
    MAXMB=$((FREEMB - FREEMB / 10 ))
    # Startwert des Schiebelreglers
    if [ $MAXMB -gt 1200 ]; then 
        SELECTMB=1024
    else
        SELECTMB=$((FREEMB / 2))
    fi


    # Fragen, wie gross der Container sein soll
    SIZE=$(zenity --scale --text="Im Verzeichnis $MOUNTPOINT sind $FREEMB MB Platz frei.\nWie groß (im MB) soll der neue Container sein?" --min-value=$MINMB --max-value=$MAXMB --value=$SELECTMB)

    # Leere Antwort: Abbrechen
    if [ x$SIZE = "x" ]; then 
        exit 1
    fi
    
    # TC erwartet die Containerröße in Bytes...
    SIZE=$((SIZE * 1024 *1024))

    # Passwort des Containers erfragen
	CONTAINER_PASS=$(zenity --entry \
				--title="Passwort festlegen" \
				--text="Geben Sie ein gutes Passwort für den neuen verschlüsselten Datencontainer an." \
				--entry-text "Passwort")

    # Kein neues Passwort angegeben: Abbrechen
    if [ $CONTAINER_PASS = "Passwort" ]; then
        exit 1
    fi

    # Container anlegen
	truecrypt 	--text \
			--filesystem=FAT \
			--volume-type=normal \
			--create  \
			--size=$SIZE \
			--encryption=AES \
			--hash=RIPEMD-160 \
			--password="$CONTAINER_PASS" \
			--keyfiles= \
			--random-source=/dev/urandom \
			$MOUNTPOINT/$CONTAINERNAME  |  zenity 	--progress \
								--width 350 \
								--auto-close \
								--no-cancel \
								--pulsate \
								--text "Bitte warten, Container wird erzeugt. Das kann mehrere Minuten dauern!" \
								--title "Container wird erzeugt"

}

case $action in 
 create) 
	create_new_container
 ;;
 mount)
	mount_container
 ;;
 umount)
	umount_container
 ;;
esac
